//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingPollApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        public string Ip_Address { get; set; }
        public int User_Id { get; set; }
        public int Question_Id { get; set; }
        public int Choice_Id { get; set; }
    }
}
